// Centralized tool metadata for ToolsJockey
import {
  DocumentDuplicateIcon,
  TableCellsIcon,
  CodeBracketIcon,
  PhotoIcon,
  BoltIcon,
  ArrowsRightLeftIcon,
  EyeDropperIcon,
  KeyIcon,
  PencilSquareIcon,
  FilmIcon,
  ScissorsIcon,
  ArchiveBoxIcon,
  CameraIcon,
  ArrowsUpDownIcon,
  SpeakerWaveIcon,
  EyeIcon,
  DocumentTextIcon,
  CalculatorIcon,
  CalendarIcon,
  BanknotesIcon,
  ReceiptPercentIcon,
  ChartBarIcon,
  CurrencyDollarIcon,
  HeartIcon,
  PresentationChartBarIcon,
  DocumentArrowDownIcon,
  DocumentArrowUpIcon,
  ArrowPathIcon,
  ArrowUpTrayIcon,
  AdjustmentsHorizontalIcon,
  PauseCircleIcon,
  ShieldCheckIcon,
  LockClosedIcon,
  DocumentTextIcon as DocumentTextIcon2,
} from '@heroicons/react/24/outline';

export type ToolBadge = 'NEW' | 'POPULAR' | 'UPDATED' | 'POWER TOOL';

export interface ToolMeta {
  id: string;
  title: string;
  path: string;
  description: string;
  icon: any;
  badges?: ToolBadge[];
  group: string;
}

export const toolsConfig: ToolMeta[] = [
  // PDF Tools
  {
    id: 'batch-pdf-form-filler',
    title: 'Batch PDF Form Filler',
    path: '/tools/batch-pdf-form-filler',
    description: 'Fill PDF forms in bulk using spreadsheet data.',
    icon: DocumentDuplicateIcon,
    badges: ['POWER TOOL'],
    group: 'pdf',
  },
  {
    id: 'pdf-suite-dashboard',
    title: 'PDF Suite (All PDF Tools)',
    path: '/pdf-tools',
    description: 'Access all PDF utilities: merge, split, compress, convert, and more.',
    icon: DocumentDuplicateIcon,
    badges: ['POPULAR'],
    group: 'pdf',
  },

  // Word & Document Tools
  {
    id: 'word-to-markdown',
    title: 'Word to Markdown Converter',
    path: '/tools/word-to-markdown',
    description: 'Convert Word documents (.docx) to Markdown format.',
    icon: PencilSquareIcon,
    group: 'word',
  },
  {
    id: 'markdown-table-generator',
    title: 'Markdown Table Generator',
    path: '/tools/markdown-table-generator',
    description: 'Generate Markdown tables from CSV or tabular data.',
    icon: CodeBracketIcon,
    badges: ['NEW'],
    group: 'word',
  },
  {
    id: 'mail-merge-tool',
    title: 'Mail Merge Tool',
    path: '/tools/mail-merge-tool',
    description: 'Merge CSV data with text templates to generate personalized documents, all client-side.',
    icon: DocumentDuplicateIcon,
    badges: ['NEW'],
    group: 'word',
  },
  
  // Video Tools
  {
    id: 'video-converter',
    title: 'Video Converter',
    path: '/tools/video-converter',
    description: 'Convert videos between formats (MP4, WebM, AVI, etc.) entirely in your browser.',
    icon: FilmIcon,
    badges: ['NEW', 'POWER TOOL'],
    group: 'media',
  },
  {
    id: 'video-clipper',
    title: 'Video Clipper',
    path: '/tools/video-clipper',
    description: 'Trim and cut videos with frame-accurate precision.',
    icon: ScissorsIcon,
    badges: ['NEW'],
    group: 'media',
  },
  {
    id: 'video-compressor',
    title: 'Video Compressor',
    path: '/tools/video-compressor',
    description: 'Reduce video file size while maintaining quality.',
    icon: ArchiveBoxIcon,
    badges: ['NEW'],
    group: 'media',
  },
  {
    id: 'frame-extractor',
    title: 'Frame Extractor',
    path: '/tools/frame-extractor',
    description: 'Extract still images from videos at specific timestamps.',
    icon: CameraIcon,
    badges: ['NEW'],
    group: 'media',
  },
  {
    id: 'video-merger',
    title: 'Video Merger',
    path: '/tools/video-merger',
    description: 'Combine multiple videos into a single file.',
    icon: ArrowsUpDownIcon,
    badges: ['NEW'],
    group: 'media',
  },
  {
    id: 'audio-extractor',
    title: 'Audio Extractor',
    path: '/tools/audio-extractor',
    description: 'Extract audio tracks from videos in multiple formats.',
    icon: SpeakerWaveIcon,
    badges: ['NEW'],
    group: 'media',
  },
  
  // Excel & CSV Tools
  {
    id: 'excel-merger-splitter',
    title: 'Excel Merger & Splitter',
    path: '/tools/excel-merger-splitter',
    description: 'Merge or split Excel sheets. Batch process .xlsx files.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'csv-merger',
    title: 'CSV Merger',
    path: '/tools/csv-merger',
    description: 'Merge multiple CSV files by rows or columns.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'csv-to-json',
    title: 'CSV to JSON Converter',
    path: '/tools/csv-to-json',
    description: 'Convert CSV files to JSON format.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'excel-to-csv',
    title: 'Excel to CSV Converter',
    path: '/tools/excel-to-csv',
    description: 'Convert Excel (.xlsx) files to CSV format with delimiter and quoting options.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'excel-to-json',
    title: 'Excel to JSON Converter',
    path: '/tools/excel-to-json',
    description: 'Convert Excel (.xlsx) files to JSON format.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'excel-to-pdf',
    title: 'Excel to PDF Converter',
    path: '/tools/excel-to-pdf',
    description: 'Convert Excel (.xlsx) files to PDF format.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'excel-to-html',
    title: 'Excel to HTML Converter',
    path: '/tools/excel-to-html',
    description: 'Convert Excel (.xlsx) files to HTML format.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'excel-to-xml',
    title: 'Excel to XML Converter',
    path: '/tools/excel-to-xml',
    description: 'Convert Excel (.xlsx) files to XML format.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'csv-to-excel',
    title: 'CSV to Excel Converter',
    path: '/tools/csv-to-excel',
    description: 'Convert CSV files to Excel (.xlsx) format with automatic column detection.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'xml-to-excel',
    title: 'XML to Excel Converter',
    path: '/tools/xml-to-excel',
    description: 'Convert XML files to Excel (.xlsx) format.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'column-filter',
    title: 'CSV/Excel Column Filter',
    path: '/tools/column-filter',
    description: 'Filter columns in CSV or Excel files.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'remove-duplicates',
    title: 'CSV/Excel Duplicate Remover',
    path: '/tools/remove-duplicates',
    description: 'Remove duplicate rows from CSV or Excel files.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'json-to-excel',
    title: 'JSON to Excel Converter',
    path: '/tools/json-to-excel',
    description: 'Convert JSON files to Excel (.xlsx) format.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  // Image Tools
  {
    id: 'image-compressor',
    title: 'Image Compressor',
    path: '/tools/image-compressor',
    description: 'Compress images to reduce file size.',
    icon: PhotoIcon,
    group: 'image',
  },
  {
    id: 'image-sharpener',
    title: 'Image Sharpener',
    path: '/tools/image-sharpener',
    description: 'Enhance image sharpness and clarity.',
    icon: PhotoIcon,
    group: 'image',
  },
  {
    id: 'image-format-converter',
    title: 'Image Format Converter',
    path: '/tools/image-format-converter',
    description: 'Convert images between formats (JPG, PNG, WebP, etc.).',
    icon: PhotoIcon,
    group: 'image',
  },
  {
    id: 'exif-remover',
    title: 'EXIF Data Remover',
    path: '/tools/exif-remover',
    description: 'Remove metadata from images for privacy.',
    icon: PhotoIcon,
    group: 'image',
  },
  {
    id: 'watermark-adder',
    title: 'Watermark Adder',
    path: '/tools/watermark-adder',
    description: 'Add text or image watermarks to photos.',
    icon: PhotoIcon,
    group: 'image',
  },
  {
    id: 'color-palette-generator',
    title: 'Color Palette Generator',
    path: '/tools/color-palette-generator',
    description: 'Generate color palettes from images or create custom ones.',
    icon: EyeDropperIcon,
    group: 'color',
  },
  {
    id: 'color-picker',
    title: 'Color Picker',
    path: '/tools/color-picker',
    description: 'Pick colors from images or create custom colors.',
    icon: EyeDropperIcon,
    group: 'color',
  },
  {
    id: 'color-format-converter',
    title: 'Color Format Converter',
    path: '/tools/color-format-converter',
    description: 'Convert between color formats (HEX, RGB, HSL, etc.).',
    icon: EyeDropperIcon,
    group: 'color',
  },
  {
    id: 'contrast-checker',
    title: 'Contrast Checker',
    path: '/tools/contrast-checker',
    description: 'Check color contrast for accessibility compliance.',
    icon: EyeDropperIcon,
    group: 'color',
  },
  {
    id: 'gradient-generator',
    title: 'Gradient Generator',
    path: '/tools/gradient-generator',
    description: 'Create beautiful CSS gradients.',
    icon: EyeDropperIcon,
    group: 'color',
  },
  // Developer Tools
  {
    id: 'json-formatter',
    title: 'JSON Formatter',
    path: '/tools/json-formatter',
    description: 'Format and validate JSON data.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'base64-encoder',
    title: 'Base64 Encoder/Decoder',
    path: '/tools/base64-encoder',
    description: 'Encode and decode Base64 strings.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'hash-generator',
    title: 'Hash Generator',
    path: '/tools/hash-generator',
    description: 'Generate MD5, SHA-1, SHA-256 hashes.',
    icon: KeyIcon,
    group: 'developer',
  },
  {
    id: 'regex-tester',
    title: 'Regex Tester',
    path: '/tools/regex-tester',
    description: 'Test and debug regular expressions.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'css-minifier',
    title: 'CSS Minifier',
    path: '/tools/css-minifier',
    description: 'Minify CSS code to reduce file size.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'text-case-converter',
    title: 'Text Case Converter',
    path: '/tools/text-case-converter',
    description: 'Convert text between different cases (camelCase, snake_case, etc.).',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'text-diff-viewer',
    title: 'Text Diff Viewer',
    path: '/tools/text-diff-viewer',
    description: 'Compare and highlight differences between text files.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'word-counter',
    title: 'Word Counter',
    path: '/tools/word-counter',
    description: 'Count words, characters, and paragraphs in text.',
    icon: DocumentTextIcon,
    group: 'developer',
  },
  {
    id: 'password-generator',
    title: 'Password Generator',
    path: '/tools/password-generator',
    description: 'Generate secure random passwords.',
    icon: KeyIcon,
    group: 'developer',
  },
  {
    id: 'qr-code-generator',
    title: 'QR Code Generator',
    path: '/tools/qr-code-generator',
    description: 'Generate QR codes for URLs, text, or contact information.',
    icon: EyeIcon,
    group: 'developer',
  },
  // Quick Tools
  {
    id: 'unit-converter',
    title: 'Unit Converter',
    path: '/tools/unit-converter',
    description: 'Convert between different units of measurement.',
    icon: ArrowsRightLeftIcon,
    group: 'quick',
  },
  {
    id: 'currency-converter',
    title: 'Currency Converter',
    path: '/tools/currency-converter',
    description: 'Convert between different currencies.',
    icon: ArrowsRightLeftIcon,
    group: 'quick',
  },
  {
    id: 'text-from-image',
    title: 'Text from Image',
    path: '/tools/text-from-image',
    description: 'Extract text from images using OCR.',
    icon: EyeIcon,
    group: 'quick',
  },
  // Converters
  {
    id: 'archive-converter',
    title: 'Archive Converter',
    path: '/tools/archive-converter',
    description: 'Convert between archive formats (ZIP, TAR, 7z, etc.).',
    icon: ArchiveBoxIcon,
    group: 'converter',
  },
  {
    id: 'batch-compressor',
    title: 'Batch Compressor',
    path: '/tools/batch-compressor',
    description: 'Compress multiple files individually with progress tracking.',
    icon: ArchiveBoxIcon,
    group: 'converter',
  },
  // Archive Tools
  {
    id: 'zip-creator',
    title: 'ZIP Creator',
    path: '/tools/zip-creator',
    description: 'Create ZIP archives with compression options.',
    icon: ArchiveBoxIcon,
    group: 'archive',
  },
  {
    id: 'zip-extractor',
    title: 'ZIP Extractor',
    path: '/tools/zip-extractor',
    description: 'Extract files from ZIP archives with selective extraction.',
    icon: ArchiveBoxIcon,
    group: 'archive',
  },
  {
    id: 'seven-zip-support',
    title: '7z Support',
    path: '/tools/seven-zip-support',
    description: 'Handle 7z format compression and extraction.',
    icon: ArchiveBoxIcon,
    group: 'archive',
  },
  {
    id: 'file-archiver',
    title: 'File Archiver',
    path: '/tools/file-archiver',
    description: 'Create various archive formats (tar, gz, bz2) with compression options.',
    icon: ArchiveBoxIcon,
    group: 'archive',
  },
  {
    id: 'archive-inspector',
    title: 'Archive Inspector',
    path: '/tools/archive-inspector',
    description: 'View archive contents without extracting. Inspect file details, sizes, and structure.',
    icon: ArchiveBoxIcon,
    group: 'archive',
  },
  {
    id: 'archive-converter',
    title: 'Archive Converter',
    path: '/tools/archive-converter',
    description: 'Convert between different archive formats with compression options.',
    icon: ArchiveBoxIcon,
    group: 'archive',
  },
  // Calculation Tools
  {
    id: 'scientific-calculator',
    title: 'Scientific Calculator',
    path: '/tools/scientific-calculator',
    description: 'Advanced mathematical operations with scientific functions.',
    icon: CalculatorIcon,
    badges: ['NEW'],
    group: 'calculation',
  },
  {
    id: 'date-calculator',
    title: 'Date Calculator',
    path: '/tools/date-calculator',
    description: 'Calculate differences, add/subtract dates and time periods.',
    icon: CalendarIcon,
    badges: ['NEW'],
    group: 'calculation',
  },
  {
    id: 'loan-calculator',
    title: 'Loan Calculator',
    path: '/tools/loan-calculator',
    description: 'Mortgage, interest, and payment calculations with amortization.',
    icon: BanknotesIcon,
    badges: ['NEW'],
    group: 'calculation',
  },
  {
    id: 'tax-calculator',
    title: 'Tax Calculator',
    path: '/tools/tax-calculator',
    description: 'Basic tax calculations and deductions for various scenarios.',
    icon: ReceiptPercentIcon,
    badges: ['NEW'],
    group: 'calculation',
  },
  {
    id: 'percentage-calculator',
    title: 'Percentage Calculator',
    path: '/tools/percentage-calculator',
    description: 'Various percentage calculations and conversions.',
    icon: ReceiptPercentIcon,
    badges: ['NEW'],
    group: 'calculation',
  },
  {
    id: 'statistics-calculator',
    title: 'Statistics Calculator',
    path: '/tools/statistics-calculator',
    description: 'Mean, median, standard deviation, and statistical analysis.',
    icon: ChartBarIcon,
    badges: ['NEW'],
    group: 'calculation',
  },
  {
    id: 'investment-calculator',
    title: 'Investment Calculator',
    path: '/tools/investment-calculator',
    description: 'Compound interest, ROI, and investment growth calculations.',
    icon: CurrencyDollarIcon,
    badges: ['NEW'],
    group: 'calculation',
  },
  {
    id: 'bmi-calculator',
    title: 'BMI Calculator',
    path: '/tools/bmi-calculator',
    description: 'Health and fitness calculations including BMI and body metrics.',
    icon: HeartIcon,
    badges: ['NEW'],
    group: 'calculation',
  },

  // Audio Tools
  {
    id: 'audio-converter',
    title: 'Audio Converter',
    path: '/tools/audio-converter',
    description: 'Convert between audio formats (MP3, WAV, OGG) client-side.',
    icon: ArrowPathIcon,
    group: 'media',
  },
  {
    id: 'audio-compressor',
    title: 'Audio Compressor',
    path: '/tools/audio-compressor',
    description: 'Reduce audio file sizes and bitrates in your browser.',
    icon: AdjustmentsHorizontalIcon,
    group: 'media',
  },
  {
    id: 'audio-merger',
    title: 'Audio Merger',
    path: '/tools/audio-merger',
    description: 'Combine multiple audio files into one.',
    icon: ArrowUpTrayIcon,
    group: 'media',
  },
  {
    id: 'audio-clipper',
    title: 'Audio Clipper',
    path: '/tools/audio-clipper',
    description: 'Cut and trim audio segments easily.',
    icon: ScissorsIcon,
    group: 'media',
  },
  {
    id: 'volume-normalizer',
    title: 'Volume Normalizer',
    path: '/tools/volume-normalizer',
    description: 'Adjust and normalize audio levels.',
    icon: SpeakerWaveIcon,
    group: 'media',
  },
  {
    id: 'audio-metadata-editor',
    title: 'Audio Metadata Editor',
    path: '/tools/audio-metadata-editor',
    description: 'Edit ID3 tags and audio properties.',
    icon: PencilSquareIcon,
    group: 'media',
  },
  {
    id: 'audio-speed-changer',
    title: 'Audio Speed Changer',
    path: '/tools/audio-speed-changer',
    description: 'Change playback speed without pitch change.',
    icon: BoltIcon,
    group: 'media',
  },
  {
    id: 'silent-audio-generator',
    title: 'Silent Audio Generator',
    path: '/tools/silent-audio-generator',
    description: 'Create silent audio files of any duration.',
    icon: PauseCircleIcon,
    group: 'media',
  },
  {
    id: 'html-minifier',
    title: 'HTML Minifier',
    path: '/tools/html-minifier',
    description: 'Compress and minify HTML code client-side.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'js-minifier',
    title: 'JavaScript Minifier',
    path: '/tools/js-minifier',
    description: 'Compress and minify JavaScript code client-side.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'code-formatter',
    title: 'Code Formatter',
    path: '/tools/code-formatter',
    description: 'Format code in multiple languages using Prettier.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'syntax-highlighter',
    title: 'Syntax Highlighter',
    path: '/tools/syntax-highlighter',
    description: 'Highlight code with themes and line numbers.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'code-diff-viewer',
    title: 'Code Diff Viewer',
    path: '/tools/code-diff-viewer',
    description: 'Compare code differences side-by-side.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'url-encoder-decoder',
    title: 'URL Encoder/Decoder',
    path: '/tools/url-encoder-decoder',
    description: 'Encode and decode URLs easily.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'html-entity-converter',
    title: 'HTML Entity Converter',
    path: '/tools/html-entity-converter',
    description: 'Convert text to and from HTML entities.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'lorem-ipsum-generator',
    title: 'Lorem Ipsum Generator',
    path: '/tools/lorem-ipsum-generator',
    description: 'Generate placeholder Lorem Ipsum text.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'image-collage-maker',
    title: 'Image Collage Maker',
    group: 'image',
    path: '/tools/image-collage-maker',
    icon: PhotoIcon,
    description: 'Combine, drag, and arrange multiple images into a single downloadable image.',
  },
  {
    id: 'image-cropper',
    title: 'Image Cropper',
    group: 'image',
    path: '/tools/image-cropper',
    icon: PhotoIcon,
    description: 'Crop images with freeform or aspect-ratio-locked selection. Download the cropped result.',
  },
  {
    id: 'image-optimizer',
    title: 'Image Optimizer',
    group: 'image',
    path: '/tools/image-optimizer',
    icon: PhotoIcon,
    description: 'Optimize images: compress, strip metadata, convert formats, and reduce file size without changing resolution.',
  },
  {
    id: 'image-downscaler',
    title: 'Image Downscaler',
    group: 'image',
    path: '/tools/image-downscaler',
    icon: PhotoIcon,
    description: 'Downscale images by dimensions or target file size. Compress, convert, and optimize images easily.',
  },
  // Privacy Tools
  {
    id: 'file-encryptor',
    title: 'File Encryptor',
    path: '/tools/file-encryptor',
    description: 'Encrypt files with AES-256 encryption. 100% client-side processing for maximum privacy.',
    icon: LockClosedIcon,
    badges: ['NEW'],
    group: 'privacy',
  },
  {
    id: 'file-decryptor',
    title: 'File Decryptor',
    path: '/tools/file-decryptor',
    description: 'Decrypt files encrypted with AES-256. Secure client-side decryption.',
    icon: LockClosedIcon,
    badges: ['NEW'],
    group: 'privacy',
  },
  {
    id: 'random-data-generator',
    title: 'Random Data Generator',
    path: '/tools/random-data-generator',
    description: 'Generate cryptographically secure random data for passwords, keys, and testing.',
    icon: BoltIcon,
    badges: ['NEW'],
    group: 'privacy',
  },
  {
    id: 'exif-data-viewer',
    title: 'EXIF Data Viewer',
    path: '/tools/exif-data-viewer',
    description: 'View detailed image metadata including camera settings, location, and timestamps.',
    icon: EyeIcon,
    badges: ['NEW'],
    group: 'privacy',
  },
  {
    id: 'secure-notes',
    title: 'Secure Notes',
    path: '/tools/secure-notes',
    description: 'Create encrypted text notes with client-side encryption. Your data never leaves your browser.',
    icon: DocumentTextIcon2,
    badges: ['NEW'],
    group: 'privacy',
  },
  {
    id: 'file-hash-verifier',
    title: 'File Hash Verifier',
    path: '/tools/file-hash-verifier',
    description: 'Verify file integrity with SHA-256, MD5, and other hash algorithms.',
    icon: ShieldCheckIcon,
    badges: ['NEW'],
    group: 'privacy',
  },
];

// Optionally, export group metadata for section headers, icons, etc.
export const toolGroups = [
  { id: 'pdf', label: '📄 PDF Tools', icon: DocumentDuplicateIcon },
  { id: 'word', label: '📝 Word & Document Tools', icon: PencilSquareIcon },
  { id: 'media', label: '🎬 Media Tools', icon: FilmIcon },
  { id: 'excelcsv', label: '📊 Excel & CSV Tools', icon: TableCellsIcon },
  { id: 'image', label: '🖼️ Image Tools', icon: PhotoIcon },
  { id: 'color', label: '🎨 Color & Design Tools', icon: EyeDropperIcon },
  { id: 'developer', label: '⚙️ Developer Tools', icon: CodeBracketIcon },
  { id: 'archive', label: '📦 Archive Tools', icon: ArchiveBoxIcon },
  { id: 'quick', label: '🔑 Quick Utilities', icon: BoltIcon },
  { id: 'converter', label: '🌍 Converters', icon: ArrowsRightLeftIcon },
  { id: 'presentation', label: '📊 Presentation Tools', icon: PresentationChartBarIcon },
  { id: 'calculation', label: '🧮 Calculation Tools', icon: CalculatorIcon },
  { id: 'privacy', label: '🔒 Privacy Tools', icon: ShieldCheckIcon },
]; 