// Centralized tool metadata for ToolsJockey
import {
  DocumentDuplicateIcon,
  TableCellsIcon,
  CodeBracketIcon,
  PhotoIcon,
  BoltIcon,
  ArrowsRightLeftIcon,
  EyeDropperIcon,
  KeyIcon,
  PencilSquareIcon,
  FilmIcon,
  ScissorsIcon,
  ArchiveBoxIcon,
  CameraIcon,
  ArrowsUpDownIcon,
  SpeakerWaveIcon,
  EyeIcon,
  DocumentTextIcon,
  CalculatorIcon,
  CalendarIcon,
  BanknotesIcon,
  ReceiptPercentIcon,
  ChartBarIcon,
  CurrencyDollarIcon,
  HeartIcon,
} from '@heroicons/react/24/outline';

export type ToolBadge = 'NEW' | 'POPULAR' | 'UPDATED' | 'POWER TOOL';

export interface ToolMeta {
  id: string;
  title: string;
  path: string;
  description: string;
  icon: any;
  badges?: ToolBadge[];
  group: string;
}

export const toolsConfig: ToolMeta[] = [
  // PDF Tools
  {
    id: 'batch-pdf-form-filler',
    title: 'Batch PDF Form Filler',
    path: '/tools/batch-pdf-form-filler',
    description: 'Fill PDF forms in bulk using spreadsheet data.',
    icon: DocumentDuplicateIcon,
    badges: ['POWER TOOL'],
    group: 'pdf',
  },
  {
    id: 'pdf-suite-dashboard',
    title: 'PDF Suite (All PDF Tools)',
    path: '/pdf-tools',
    description: 'Access all PDF utilities: merge, split, compress, convert, and more.',
    icon: DocumentDuplicateIcon,
    badges: ['POPULAR'],
    group: 'pdf',
  },

  // Word & Document Tools
  {
    id: 'word-to-markdown',
    title: 'Word to Markdown Converter',
    path: '/tools/word-to-markdown',
    description: 'Convert Word documents (.docx) to Markdown format.',
    icon: PencilSquareIcon,
    group: 'word',
  },
  {
    id: 'markdown-table-generator',
    title: 'Markdown Table Generator',
    path: '/tools/markdown-table-generator',
    description: 'Generate Markdown tables from CSV or tabular data.',
    icon: CodeBracketIcon,
    badges: ['NEW'],
    group: 'word',
  },
  {
    id: 'mail-merge-tool',
    title: 'Mail Merge Tool',
    path: '/tools/mail-merge-tool',
    description: 'Merge CSV data with text templates to generate personalized documents, all client-side.',
    icon: DocumentDuplicateIcon,
    badges: ['NEW'],
    group: 'word',
  },
  
  // Video Tools
  {
    id: 'video-converter',
    title: 'Video Converter',
    path: '/tools/video-converter',
    description: 'Convert videos between formats (MP4, WebM, AVI, etc.) entirely in your browser.',
    icon: FilmIcon,
    badges: ['NEW', 'POWER TOOL'],
    group: 'video',
  },
  {
    id: 'video-clipper',
    title: 'Video Clipper',
    path: '/tools/video-clipper',
    description: 'Trim and cut videos with frame-accurate precision.',
    icon: ScissorsIcon,
    badges: ['NEW'],
    group: 'video',
  },
  {
    id: 'video-compressor',
    title: 'Video Compressor',
    path: '/tools/video-compressor',
    description: 'Reduce video file size while maintaining quality.',
    icon: ArchiveBoxIcon,
    badges: ['NEW'],
    group: 'video',
  },
  {
    id: 'frame-extractor',
    title: 'Frame Extractor',
    path: '/tools/frame-extractor',
    description: 'Extract still images from videos at specific timestamps.',
    icon: CameraIcon,
    badges: ['NEW'],
    group: 'video',
  },
  {
    id: 'video-merger',
    title: 'Video Merger',
    path: '/tools/video-merger',
    description: 'Combine multiple videos into a single file.',
    icon: ArrowsUpDownIcon,
    badges: ['NEW'],
    group: 'video',
  },
  {
    id: 'audio-extractor',
    title: 'Audio Extractor',
    path: '/tools/audio-extractor',
    description: 'Extract audio tracks from videos in multiple formats.',
    icon: SpeakerWaveIcon,
    badges: ['NEW'],
    group: 'video',
  },
  
  // Excel & CSV Tools
  {
    id: 'excel-merger-splitter',
    title: 'Excel Merger & Splitter',
    path: '/tools/excel-merger-splitter',
    description: 'Merge or split Excel sheets. Batch process .xlsx files.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'csv-merger',
    title: 'CSV Merger',
    path: '/tools/csv-merger',
    description: 'Merge multiple CSV files by rows or columns.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'csv-to-json',
    title: 'CSV to JSON Converter',
    path: '/tools/csv-to-json',
    description: 'Convert CSV files to JSON format.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'column-filter',
    title: 'CSV/Excel Column Filter',
    path: '/tools/column-filter',
    description: 'Filter columns in CSV or Excel files.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'remove-duplicates',
    title: 'CSV/Excel Duplicate Remover',
    path: '/tools/remove-duplicates',
    description: 'Remove duplicate rows from CSV or Excel files.',
    icon: TableCellsIcon,
    group: 'excelcsv',
  },
  {
    id: 'excel-to-formats',
    title: 'Excel to Everything Converter',
    path: '/tools/excel-to-formats',
    description: 'Convert Excel files to CSV, JSON, HTML, PDF, Google Sheets, and more. Batch, privacy-first, and pro-grade.',
    icon: TableCellsIcon,
    badges: ['NEW'],
    group: 'excelcsv',
  },
  // Image Tools
  {
    id: 'image-compressor',
    title: 'Image Compressor',
    path: '/tools/image-compressor',
    description: 'Compress images to reduce file size.',
    icon: PhotoIcon,
    group: 'image',
  },
  {
    id: 'image-sharpener',
    title: 'Image Sharpener',
    path: '/tools/image-sharpener',
    description: 'Enhance image sharpness and clarity.',
    icon: PhotoIcon,
    group: 'image',
  },
  {
    id: 'image-format-converter',
    title: 'Image Format Converter',
    path: '/tools/image-format-converter',
    description: 'Convert images between formats (JPG, PNG, WebP, etc.).',
    icon: PhotoIcon,
    group: 'image',
  },
  {
    id: 'exif-remover',
    title: 'EXIF Data Remover',
    path: '/tools/exif-remover',
    description: 'Remove metadata from images for privacy.',
    icon: PhotoIcon,
    group: 'image',
  },
  {
    id: 'watermark-adder',
    title: 'Watermark Adder',
    path: '/tools/watermark-adder',
    description: 'Add text or image watermarks to photos.',
    icon: PhotoIcon,
    group: 'image',
  },
  {
    id: 'color-palette-generator',
    title: 'Color Palette Generator',
    path: '/tools/color-palette-generator',
    description: 'Generate color palettes from images or create custom ones.',
    icon: EyeDropperIcon,
    group: 'color',
  },
  {
    id: 'color-picker',
    title: 'Color Picker',
    path: '/tools/color-picker',
    description: 'Pick colors from images or create custom colors.',
    icon: EyeDropperIcon,
    group: 'color',
  },
  {
    id: 'color-format-converter',
    title: 'Color Format Converter',
    path: '/tools/color-format-converter',
    description: 'Convert between color formats (HEX, RGB, HSL, etc.).',
    icon: EyeDropperIcon,
    group: 'color',
  },
  {
    id: 'contrast-checker',
    title: 'Contrast Checker',
    path: '/tools/contrast-checker',
    description: 'Check color contrast for accessibility compliance.',
    icon: EyeDropperIcon,
    group: 'color',
  },
  {
    id: 'gradient-generator',
    title: 'Gradient Generator',
    path: '/tools/gradient-generator',
    description: 'Create beautiful CSS gradients.',
    icon: EyeDropperIcon,
    group: 'color',
  },
  // Developer Tools
  {
    id: 'json-formatter',
    title: 'JSON Formatter',
    path: '/tools/json-formatter',
    description: 'Format and validate JSON data.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'base64-encoder',
    title: 'Base64 Encoder/Decoder',
    path: '/tools/base64-encoder',
    description: 'Encode and decode Base64 strings.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'hash-generator',
    title: 'Hash Generator',
    path: '/tools/hash-generator',
    description: 'Generate MD5, SHA-1, SHA-256 hashes.',
    icon: KeyIcon,
    group: 'developer',
  },
  {
    id: 'regex-tester',
    title: 'Regex Tester',
    path: '/tools/regex-tester',
    description: 'Test and debug regular expressions.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'css-minifier',
    title: 'CSS Minifier',
    path: '/tools/css-minifier',
    description: 'Minify CSS code to reduce file size.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'text-case-converter',
    title: 'Text Case Converter',
    path: '/tools/text-case-converter',
    description: 'Convert text between different cases (camelCase, snake_case, etc.).',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'text-diff-viewer',
    title: 'Text Diff Viewer',
    path: '/tools/text-diff-viewer',
    description: 'Compare and highlight differences between text files.',
    icon: CodeBracketIcon,
    group: 'developer',
  },
  {
    id: 'word-counter',
    title: 'Word Counter',
    path: '/tools/word-counter',
    description: 'Count words, characters, and paragraphs in text.',
    icon: DocumentTextIcon,
    group: 'developer',
  },
  {
    id: 'password-generator',
    title: 'Password Generator',
    path: '/tools/password-generator',
    description: 'Generate secure random passwords.',
    icon: KeyIcon,
    group: 'developer',
  },
  {
    id: 'qr-code-generator',
    title: 'QR Code Generator',
    path: '/tools/qr-code-generator',
    description: 'Generate QR codes for URLs, text, or contact information.',
    icon: EyeIcon,
    group: 'developer',
  },
  // Quick Tools
  {
    id: 'unit-converter',
    title: 'Unit Converter',
    path: '/tools/unit-converter',
    description: 'Convert between different units of measurement.',
    icon: ArrowsRightLeftIcon,
    group: 'quick',
  },
  {
    id: 'currency-converter',
    title: 'Currency Converter',
    path: '/tools/currency-converter',
    description: 'Convert between different currencies.',
    icon: ArrowsRightLeftIcon,
    group: 'quick',
  },
  {
    id: 'text-from-image',
    title: 'Text from Image',
    path: '/tools/text-from-image',
    description: 'Extract text from images using OCR.',
    icon: EyeIcon,
    group: 'quick',
  },
  // Converters
  {
    id: 'archive-converter',
    title: 'Archive Converter',
    path: '/tools/archive-converter',
    description: 'Convert between archive formats (ZIP, TAR, 7z, etc.).',
    icon: ArchiveBoxIcon,
    group: 'converter',
  },
  {
    id: 'batch-compressor',
    title: 'Batch Compressor',
    path: '/tools/batch-compressor',
    description: 'Compress multiple files individually with progress tracking.',
    icon: ArchiveBoxIcon,
    group: 'converter',
  },
  // Archive Tools
  {
    id: 'zip-creator',
    title: 'ZIP Creator',
    path: '/tools/zip-creator',
    description: 'Create ZIP archives with compression options.',
    icon: ArchiveBoxIcon,
    group: 'archive',
  },
  {
    id: 'zip-extractor',
    title: 'ZIP Extractor',
    path: '/tools/zip-extractor',
    description: 'Extract files from ZIP archives with selective extraction.',
    icon: ArchiveBoxIcon,
    group: 'archive',
  },
  {
    id: 'seven-zip-support',
    title: '7z Support',
    path: '/tools/seven-zip-support',
    description: 'Handle 7z format compression and extraction.',
    icon: ArchiveBoxIcon,
    group: 'archive',
  },
  {
    id: 'file-archiver',
    title: 'File Archiver',
    path: '/tools/file-archiver',
    description: 'Create various archive formats (tar, gz, bz2) with compression options.',
    icon: ArchiveBoxIcon,
    group: 'archive',
  },
  {
    id: 'archive-inspector',
    title: 'Archive Inspector',
    path: '/tools/archive-inspector',
    description: 'View archive contents without extracting. Inspect file details, sizes, and structure.',
    icon: ArchiveBoxIcon,
    group: 'archive',
  },
  {
    id: 'archive-converter',
    title: 'Archive Converter',
    path: '/tools/archive-converter',
    description: 'Convert between different archive formats with compression options.',
    icon: ArchiveBoxIcon,
    group: 'archive',
  },
  // Calculation Tools
  {
    id: 'scientific-calculator',
    title: 'Scientific Calculator',
    path: '/tools/scientific-calculator',
    description: 'Advanced mathematical operations with scientific functions.',
    icon: CalculatorIcon,
    badges: ['NEW'],
    group: 'calculation',
  },
  {
    id: 'date-calculator',
    title: 'Date Calculator',
    path: '/tools/date-calculator',
    description: 'Calculate differences, add/subtract dates and time periods.',
    icon: CalendarIcon,
    badges: ['NEW'],
    group: 'calculation',
  },
  {
    id: 'loan-calculator',
    title: 'Loan Calculator',
    path: '/tools/loan-calculator',
    description: 'Mortgage, interest, and payment calculations with amortization.',
    icon: BanknotesIcon,
    badges: ['NEW'],
    group: 'calculation',
  },
  {
    id: 'tax-calculator',
    title: 'Tax Calculator',
    path: '/tools/tax-calculator',
    description: 'Basic tax calculations and deductions for various scenarios.',
    icon: ReceiptPercentIcon,
    badges: ['NEW'],
    group: 'calculation',
  },
  {
    id: 'percentage-calculator',
    title: 'Percentage Calculator',
    path: '/tools/percentage-calculator',
    description: 'Various percentage calculations and conversions.',
    icon: ReceiptPercentIcon,
    badges: ['NEW'],
    group: 'calculation',
  },
  {
    id: 'statistics-calculator',
    title: 'Statistics Calculator',
    path: '/tools/statistics-calculator',
    description: 'Mean, median, standard deviation, and statistical analysis.',
    icon: ChartBarIcon,
    badges: ['NEW'],
    group: 'calculation',
  },
  {
    id: 'investment-calculator',
    title: 'Investment Calculator',
    path: '/tools/investment-calculator',
    description: 'Compound interest, ROI, and investment growth calculations.',
    icon: CurrencyDollarIcon,
    badges: ['NEW'],
    group: 'calculation',
  },
  {
    id: 'bmi-calculator',
    title: 'BMI Calculator',
    path: '/tools/bmi-calculator',
    description: 'Health and fitness calculations including BMI and body metrics.',
    icon: HeartIcon,
    badges: ['NEW'],
    group: 'calculation',
  },
];

// Optionally, export group metadata for section headers, icons, etc.
export const toolGroups = [
  { id: 'pdf', label: '📄 PDF Tools', icon: DocumentDuplicateIcon },
  { id: 'word', label: '📝 Word & Document Tools', icon: PencilSquareIcon },
  { id: 'video', label: '🎬 Video Tools', icon: FilmIcon },
  { id: 'excelcsv', label: '📊 Excel & CSV Tools', icon: TableCellsIcon },
  { id: 'image', label: '🖼️ Image Tools', icon: PhotoIcon },
  { id: 'color', label: '🎨 Color & Design Tools', icon: EyeDropperIcon },
  { id: 'developer', label: '⚙️ Developer Tools', icon: CodeBracketIcon },
  { id: 'archive', label: '📦 Archive Tools', icon: ArchiveBoxIcon },
  { id: 'quick', label: '🔑 Quick Utilities', icon: BoltIcon },
  { id: 'converter', label: '🌍 Converters', icon: ArrowsRightLeftIcon },
]; 